### ISSUE TITLE
Iso Evo Pipeline bug

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#15]
active branch=release/py3/v18.2

active analyses=UW142:B11-01A

description="Cannot get past the "Fit IsoEvo" node of the Iso Evo pipline. Raw data will not load "

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 334, in run
    self._run_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 524, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 503, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 716, in run_pipeline
    node.run(state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 283, in run
    fs = progress_loader(unks, self._assemble_result, threshold=1, step=10)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 102, in progress_loader
    items = list(gen())
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 87, in gen
    for ri in r:
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 311, in _assemble_result
    i, e = iso.value, iso.error
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\isotope.py", line 342, in value
    v = self.regressor.predict(0)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\isotope.py", line 420, in regressor
    reg.calculate()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\regression\ols_regressor.py", line 103, in calculate
    fx, fy = self.calculate_filtered_data()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\regression\base_regressor.py", line 141, in calculate_filtered_data
    outliers = self.calculate_outliers(nsigma=fod.get('std_devs', 2))
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\regression\base_regressor.py", line 196, in calculate_outliers
    s = self.std()
TypeError: 'numpy.float64' object is not callable

```

**Comment by aschaen** [comment]
fixed, ok to close
