### ISSUE TITLE
Blank Pipeline-extract device

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#18]
active branch=release/py3/v18.2

active analyses=UW142:D33-01A,UW142:D33-01B,UW142:D33-01C,UW142:D33-01D,UW142:D33-01E,UW142:D33-01F,UW142:D33-01G,UW142:D33-01H,UW142:D33-01I,UW142:D33-01J,UW142:D33-01K,UW142:D33-01L,UW142:D33-01M,UW142:D33-01N,UW142:D33-01O,UW142:D33-01P,UW142:D33-01Q,UW142:D33-01R,UW142:D33-01S,UW142:D33-01T,UW142:D33-01U,UW142:D33-01V,UW142:D33-01W,UW142:D33-01X,UW142:D33-01Y,UW142:D33-01Z,UW142:D33-01AA,UW142:D33-01AB,UW142:D33-01AC,UW142:D33-01AD,UW142:D33-01AE,UW142:D33-01AF,UW142:D33-01AG,UW142:D33-01AH,UW142:D33-01AI,UW142:D33-01AJ,UW142:D33-01AK,UW142:D33-01AL,UW142:D33-01AM,UW142:D33-01AN,UW142:D33-01AO,UW142:D33-01AP,UW142:D33-01AQ,UW142:D33-01AR,UW142:D33-01AS,UW142:D33-01AT,UW142:D33-01AU,UW142:D33-01AV,UW142:D33-01AW,UW142:D33-01AX,UW142:D33-01AY,UW142:D33-01AZ,UW142:D33-01BA,UW142:D33-01BB,UW142:D33-01BC,UW142:D33-01BD,UW142:D33-01BE,UW142:D33-01BF,UW142:D33-01BG,UW142:D33-01BH,UW142:D33-01BI,UW142:D33-01BJ,UW142:D33-01BK,UW142:D33-01BL,UW142:D33-01BM,UW142:D33-01BN,UW142:D33-01BO,UW142:D33-01BP,UW142:D33-01BQ,UW142:D33-01BR,UW142:D33-01BS,UW142:D33-01BT,UW142:D33-01BU,UW142:D33-01BV,UW142:D33-01BW,UW142:D33-01BX,UW142:D33-01BY,UW142:D33-01BZ,UW142:D33-01CA,UW142:D33-01CB,UW142:D33-01CC,UW142:D33-01CD

description="this bug report is appearing regardless of if I have graphical filter and/or extract device checked or unchecked"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 323, in run
    self._run_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 507, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 486, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 716, in run_pipeline
    node.run(state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\find.py", line 324, in run
    if self._run_group(state, gid, list(ans)):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\find.py", line 333, in _run_group
    mass_spectrometers=self.mass_spectrometer if self.use_mass_sepctrometer else '',
AttributeError: 'FindBlanksNode' object has no attribute 'use_mass_sepctrometer'

```

**Comment by pesobol** [comment]
seems fixed
