### ISSUE TITLE
Recalling analyses bug

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#19]
active branch=release/py3/v18.2

active analyses=UW142:D33-01D

description="recalling an analysis is not working from either the recall tab or doubling clicking an analysis in the anlayses pane"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 617, in _handle_recall
    self.recall(new)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\envisage\browser\browser_task.py", line 137, in recall
    self._open_recall_editors(ans)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\envisage\browser\browser_task.py", line 306, in _open_recall_editors
    av.main_view.set_options(rec, self.recall_configurer.recall_options)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\analyses\view\main_view.py", line 69, in set_options
    self.load(an, True)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\analyses\view\main_view.py", line 72, in load
    self._load(an)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\analyses\view\main_view.py", line 79, in _load
    self.load_extraction(an)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\processing\analyses\view\main_view.py", line 164, in load_extraction
    units='s'),
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'value' trait of an ExtractionValue instance must be a string or a float or an integer (int or long) or None, but a value of [] <class 'list'> was specified.

```

**Comment by jirhiker** [comment]
There is an issue with the format of the extraction json file you are saving. 

extract_value needs to be a number but you are saving it as a list
as an example

```
{
    "beam_diameter": "3.0", 
    "cleanup_duration": 10.0, 
    "commit": "a8c2af6c8457fcd1d6947930b4f67826a0776876", 
    "extract_device": "Fusions Diode", 
    "extract_duration": 40.0, 
    "extract_units": "", 
    "extract_value": 0.4, 
    "pattern": "", 
    "positions": [
        {
            "is_degas": false, 
            "position": 60, 
            "x": null, 
            "y": null, 
            "z": null
        }
    ], 
    "ramp_duration": 0.0, 
    "ramp_rate": 0.0, 
    "request": "", 
    "response": "", 
    "tray": "", 
    "weight": 10.2
}
```

**Comment by aschaen** [comment]
fixed, ok to close
