### ISSUE TITLE
save table

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#20]
active branch=release/py3/v18.2

active analyses=UW142:D33-01A,UW142:D33-01B,UW142:D33-01C,UW142:D33-01D,UW142:D33-01E,UW142:D33-01F,UW142:D33-01G

description="Tried to save Table and when I went to choose the directory for it, error message appeared"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 303, in save_table
    writer.build(run_groups, options=options)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tables\xlsx_table_writer.py", line 103, in build
    self._workbook.close()
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\xlsxwriter\workbook.py", line 311, in close
    self._store_workbook()
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\xlsxwriter\workbook.py", line 640, in _store_workbook
    allowZip64=self.allow_zip64)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:/test1.xlsx'

```

**Comment by jirhiker** [comment]
the raregas user does not have permission to save to the C:/ directory(?) 

1) let pychron save the file to Pychron/data/tables or 2) choose a directory that the user has permission to save to e.g C:/Users/raregas/documents

**Comment by aschaen** [comment]
no longer using this function, using the table pipeline instead so ok to close this issue
