### ISSUE TITLE
IC factor pipeline

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#21]
active branch=release/py3/v18.2

active analyses=NCocktail1-796A,NCocktail1-797A,NCocktail1-798A,NCocktail1-799A,NCocktail1-800A,NCocktail1-801A,NCocktail1-802A,NCocktail1-803A,NCocktail1-804A,NCocktail1-805A,NCocktail1-806A,NCocktail1-807A,NCocktail1-808A,NCocktail1-809A,NCocktail1-810A,NCocktail1-811A,NCocktail1-812A,NCocktail1-813A,NCocktail1-814A,NCocktail1-815A,NCocktail1-816A,NCocktail1-817A,NCocktail1-818A,NCocktail1-819A,NCocktail1-820A,NCocktail1-821A,NCocktail1-822A,NCocktail1-823A,NCocktail1-824A,NCocktail1-825A,NCocktail1-826A,NCocktail1-827A,NCocktail1-828A,NCocktail1-829A,NCocktail1-830A,NCocktail1-831A,NCocktail1-832A,NCocktail1-833A,NCocktail1-834A,NCocktail1-835A,NCocktail1-836A,NCocktail1-837A,NCocktail1-838A,NCocktail1-839A,NCocktail1-840A,NCocktail1-841A,NCocktail1-842A,NCocktail1-843A,NCocktail1-844A,NCocktail1-845A,NCocktail1-846A,NCocktail1-847A,NCocktail1-848A,NCocktail1-849A,NCocktail1-850A,NCocktail1-851A,NCocktail1-852A,NCocktail1-853A,NCocktail1-854A,NCocktail1-855A,NCocktail1-856A,NCocktail1-857A,NCocktail1-858A,NCocktail1-859A,NCocktail1-860A,NCocktail1-861A,NCocktail1-862A

description="after references node is green, this appears right before "Fit ICFctor" node "

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 325, in run
    self._run_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 509, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 488, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 718, in run_pipeline
    node.run(state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 118, in run
    self.editor.force_update(force=True)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\plot\editors\figure_editor.py", line 84, in force_update
    model = self._figure_model_factory()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\plot\editors\intercalibration_factor_editor.py", line 38, in _figure_model_factory
    analysis_groups=self.analysis_groups,
AttributeError: 'IntercalibrationFactorEditor' object has no attribute 'analysis_groups'

```

**Comment by pesobol** [comment]
ok to close
