### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by aschaen** [WiscAr/pychron#22]
when selecting an analysis in the analyses pane and using the "tag" button multiple bug reports appear. I seem to be unable to submit those directly so I've copied the info and pasted below. Tagging is not working right now, I am unable to set tagging as "omit" or "invalid" from the analyses pane.  

Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
pyodbc.IntegrityError: ('23000', '[23000] [Microsoft][SQL Server Native Client 11.0][SQL Server]The UPDATE statement conflicted with the FOREIGN KEY constraint "AnalysisChangeTbl_ibfk_1". The conflict occurred in database "PYCHRON", table "dbo.UserTbl", column \'name\'. (547) (SQLExecDirectW); [23000] [Microsoft][SQL Server Native Client 11.0][SQL Server]The statement has been terminated. (3621)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 248, in set_tag
    self.dvc.tag_items(tag, items, note)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc.py", line 1256, in tag_items
    self.set_analysis_tag(it, tag)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc_database.py", line 317, in set_analysis_tag
    sess.add(change)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\database\core\database_adapter.py", line 144, in __exit__
    self._parent.close_session()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\database\core\database_adapter.py", line 280, in close_session
    self.session.flush()
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
    flush_context.execute()
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\persistence.py", line 177, in save_obj
    mapper, table, update)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\orm\persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\sqlalchemy\engine\default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (pyodbc.IntegrityError) ('23000', '[23000] [Microsoft][SQL Server Native Client 11.0][SQL Server]The UPDATE statement conflicted with the FOREIGN KEY constraint "AnalysisChangeTbl_ibfk_1". The conflict occurred in database "PYCHRON", table "dbo.UserTbl", column \'name\'. (547) (SQLExecDirectW); [23000] [Microsoft][SQL Server Native Client 11.0][SQL Server]The statement has been terminated. (3621)') [SQL: 'UPDATE [AnalysisChangeTbl] SET tag=?, [user]=? WHERE [AnalysisChangeTbl].[idanalysischangeTbl] = ?'] [parameters: ('omit', 'root', 5504)] (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by jirhiker** [comment]
Try adding the user "root" to the UserTbl and see if that fixes this problem

**Comment by aschaen** [comment]
worked,  ok to close
