### ISSUE TITLE
blan pipeline

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#24]
active branch=release/py3/v18.2

active analyses=NBlank1-3076A,NBlank1-3077A,NBlank1-3078A,NBlank1-3079A,NBlank1-3080A,NBlank1-3081A,NBlank1-3082A,NBlank1-3083A,NBlank1-3084A,NBlank1-3085A,NBlank1-3086A,NBlank1-3087A,NBlank1-3088A,NBlank1-3089A,NBlank1-3090A,NBlank1-3091A,NBlank1-3092A,NBlank1-3093A,NBlank1-3094A,NBlank1-3095A,NBlank1-3096A,NBlank1-3097A,NBlank1-3098A,NBlank1-3099A,NBlank1-3100A

description="error appears at the "save blank" node while it is orange, doesnt turn green. The saving loading bar freezes also"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 328, in resume
    self._resume_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 506, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 488, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 618, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 718, in run_pipeline
    node.run(state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\persist.py", line 166, in run
    progress_iterator(state.unknowns, wrapper, threshold=1)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 146, in progress_iterator
    gen(progress)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 138, in gen
    func(x, prog, i, n)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\persist.py", line 165, in <lambda>
    state.saveable_keys, state.references)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\persist.py", line 178, in _save_blanks
    self.dvc.save_blanks(ai, saveable_keys, references)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc.py", line 521, in save_blanks
    ai.dump_blanks(keys, refs, reviewed=True)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc_analysis.py", line 418, in dump_blanks
    blank = isos.get(k, {})
AttributeError: 'list' object has no attribute 'get'

```

**Comment by aschaen** [comment]
appears to be fixed on our end, ok to close
