### ISSUE TITLE
Labnumber

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#25]
active branch=release/py3/v18.2

active analyses=

description="Cannot open Labnumer window "

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\entry\tasks\labnumber\actions.py", line 33, in perform
    app.get_task(pid)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\envisage\tasks\base_tasks_application.py", line 124, in get_task
    win = self.create_window(w)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\envisage\ui\tasks\tasks_application.py", line 216, in create_window
    window.add_task(task)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\task_window.py", line 189, in add_task
    dock_pane.create(self.control)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\tasks\dock_pane.py", line 64, in create
    contents = self.create_contents(control)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\traits_dock_pane.py", line 52, in create_contents
    self.ui = self.edit_traits(kind='subpanel', parent=parent)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\has_traits.py", line 1871, in edit_traits
    handler, id, scrollable, args )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\view.py", line 433, in ui
    ui.ui( parent, kind )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\ui.py", line 222, in ui
    self.rebuild( self, parent )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\toolkit.py", line 141, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 76, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 82, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "C:\Users\raregas\.pychron.0\pychron\launchers\helpers.py", line 136, in __init__
    self.control = panel(ui)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 590, in __init__
    layout = self._add_groups(content, inner)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 669, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\ui_panel.py", line 860, in _add_items
    editor.prepare(inner)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\editor.py", line 156, in prepare
    self.init( parent )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\enum_editor.py", line 187, in init
    super( SimpleEditor, self ).init( parent )
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\enum_editor.py", line 80, in init
    self.values_changed()
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traitsui\qt4\enum_editor.py", line 142, in values_changed
    enum_values_changed( self._value(), self.string_value )
  File "<string>", line 1, in <lambda>
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc_irradiationable.py", line 65, in _get_irradiations
    db = self.get_database()
AttributeError: 'LabnumberEntry' object has no attribute 'get_database'

```

**Comment by aschaen** [comment]
fixed, ok to close
