### ISSUE TITLE
I have no clue why there is an error

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#43]
active branch=develop

active analyses=UW147:C47-01A,UW147:C47-01B,UW147:C47-01C,UW147:C47-01D,UW147:C47-01E,UW147:C47-01F,UW147:C47-01G,UW147:C47-01H,UW147:C47-01I,UW147:C47-01J,UW147:C47-01K,UW147:C47-01L,UW147:C47-01M,UW147:C47-01N,UW147:C47-01O,UW147:C47-01P,UW147:C47-01Q,UW147:C47-01R,UW147:C47-01S,UW147:C47-01T,UW147:C47-01U,UW147:C47-01V,UW147:C47-01W,UW147:C47-01X,UW147:C47-01Y

description="can you identify which file is problematic?"

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 347, in run
    self._run_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 534, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 513, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 723, in run_pipeline
    node.run(state)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 425, in run
    fs = progress_loader(unks, self._assemble_result, threshold=1, step=10)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 102, in progress_loader
    items = list(gen())
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\progress.py", line 87, in gen
    for ri in r:
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\fit.py", line 438, in _assemble_result
    xi.load_raw_data(self._keys)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc_analysis.py", line 279, in load_raw_data
    data = format_blob(sn.get('blob', ''))
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\helpers\binpack.py", line 25, in format_blob
    return base64.b64decode(blob)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\base64.py", line 81, in b64decode
    s = _bytes_from_decode_data(s)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

```

**Comment by jirhiker** [comment]
suggests a corrupt/incomplete raw data file. the raw data (time vs intensity) files are located in Pychron/data/.dvc/repositories/<relevant_repo_name>/.data
