### ISSUE TITLE
pychron appears to not like Lat Long in south America (ie negative values for both)

### ISSUE THREAD

**Issue by wiscarlab** [WiscAr/pychron#44]
active branch=develop

active analyses=UW147:A3-01J

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\interpreted_age_factory.py", line 118, in _sync_metadata_button_fired
    self.dvc.sync_ia_metadata(it)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc_database.py", line 221, in sync_ia_metadata
    setattr(ia, attr, info.get(attr))
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\traits\trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'unit' trait of an InterpretedAgeGroup instance must be a string, but a value of None <class 'NoneType'> was specified.

```

**Comment by jirhiker** [comment]
unrelated to lat/long

Issue is that 'unit' is NULL in the database. As a temporary work around in the SampleTbl for the sample of interest set the value of unit to something other than NULL (e.g. an empty string, or the name of the stratigraphy unit this sample belongs to)
