### ISSUE TITLE
bug after running a blank

### ISSUE THREAD

**Issue by jirhiker** [WiscAr/pychron#52]
active branch=develop

active analyses=ba-01-n-314

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\helpers\exception_helper.py", line 285, in run_with_except_hook
    run_old(*args, **kw)
  File "c:\users\raregas\anaconda3\envs\pychron3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 510, in _execute
    self._execute_queue(i, exp)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 649, in _execute_queue
    self._join_run(spec, run)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 748, in _join_run
    self._do_run(run)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 801, in _do_run
    if not getattr(self, step)(run):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 1110, in _measurement
    if not ai.do_measurement():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\automated_run\automated_run.py", line 1251, in do_measurement
    trap=sm.read_trap_current(),
  File "C:\Users\raregas\.pychron.0\pychron\pychron\spectrometer\base_spectrometer_manager.py", line 39, in read_trap_current
    return self.spectrometer.source.read_trap_current()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\spectrometer\isotopx\source\ngx.py", line 41, in read_trap_current
    if ',' in resp:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by jirhiker** [comment]
seemingly another issue with poor comms between pychron and iconia
