### ISSUE TITLE
blank bug

### ISSUE THREAD

**Issue by jirhiker** [WiscAr/pychron#74]
active branch=dev/dr

active analyses=ba-01-N-2448,ba-01-N-2449,ba-01-N-2450,ba-01-N-2451,ba-01-N-2452,ba-01-N-2453,ba-01-N-2454,ba-01-N-2455,ba-01-N-2456,ba-01-N-2457,ba-01-N-2458,ba-01-N-2459,ba-01-N-2460

description="trying to iso evo some blanks from a queue I did last night. air and fusions were fine. "

Traceback
```
Traceback (most recent call last):
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\ui\qt4\action\action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\pyface\tasks\action\listening_action.py", line 58, in perform
    method()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 348, in run
    self._run_pipeline()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 535, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\tasks\task.py", line 514, in _run
    if not getattr(self.engine, func)():
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\engine.py", line 729, in run_pipeline
    if not node.pre_run(state, configure=configure):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 247, in pre_run
    return super(UnknownNode, self).pre_run(state, configure=True)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\base.py", line 109, in pre_run
    if self.configure(refresh=False, pre_run=True):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 130, in configure
    return self.set_browser_analyses()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 74, in set_browser_analyses
    is_append, analyses = self.get_browser_analyses()
  File "C:\Users\raregas\.pychron.0\pychron\pychron\pipeline\nodes\data.py", line 70, in get_browser_analyses
    records = self.dvc.make_analyses(records)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc.py", line 868, in make_analyses
    branches = {ei: get_repository_branch(repository_path(ei)) for ei in exps}
  File "C:\Users\raregas\.pychron.0\pychron\pychron\dvc\dvc.py", line 868, in <dictcomp>
    branches = {ei: get_repository_branch(repository_path(ei)) for ei in exps}
  File "C:\Users\raregas\.pychron.0\pychron\pychron\git_archive\repo_manager.py", line 45, in get_repository_branch
    r = Repo(path)
  File "C:\Users\jross\AppData\Local\conda\conda\envs\pychron3\lib\site-packages\git\repo\base.py", line 161, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\raregas\Pychron3\data\.dvc\repositories

```

**Comment by jirhiker** [comment]
there is likely a bogus analysis in your run selection
