### ISSUE TITLE
blank air error on ngx queue

### ISSUE THREAD

**Issue by bjicha** [WiscAr/pychron#78]
active branch=dev/dc

active analyses=

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 1198, in _make_run
    pb = self._prev_blanks[spec.analysis_type]
KeyError: 'blank_air'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\raregas\.pychron.0\pychron\pychron\core\helpers\exception_helper.py", line 285, in run_with_except_hook
    run_old(*args, **kw)
  File "c:\users\raregas\anaconda3\envs\pychron3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 511, in _execute
    self._execute_queue(i, exp)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 620, in _execute_queue
    run = self._make_run(spec)
  File "C:\Users\raregas\.pychron.0\pychron\pychron\experiment\experiment_executor.py", line 1200, in _make_run
    pb = self._prev_blanks['blank']
KeyError: 'blank'

```

**Comment by jirhiker** [comment]
this issue is resolved on the NMGRL/dev/dc branch

e.g
```
        try:
            pb = self._prev_blanks[spec.analysis_type]
        except KeyError:
            pb = self._prev_blanks.get('blank', ('', {}))
```
